bodos/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'bodos'

urlpatterns = [
    #-- bodos/ --
    path('', views.index, name = 'index'),

    #-- bodos/login --
    path('login', views.login, name = 'login'),

    #-- bodos/register --
    path('register', views.register, name = 'register'),

    # #-- bodos/about --
    # path('', views.about, name = 'about'),
    #
    # #-- bodos/datasets --
    # path('', views.datasets, name = 'datasets'),
    #
    # #-- bodos/problemsets --
    # path('', views.problemsets, name = 'problemsets'),
    #
    # #-- bodos/functions --
    # path('', views.functions, name = 'functions'),
]

bodosProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('bodos/', include('bodos.urls')),

]

bodos/models.py
from django.db import models

# Create your models here.

bodos/views.py
from django.shortcuts import render


def index(request):
    return render( request, 'bodos/index.html')

def login(request):
    return render( request, 'bodos/login.html')

def register(request):
    return render( request, 'bodos/register.html')

bodos/templates/bodos/details.html
{% extends 'bodos/base.html' %}

{% load staticfiles %}

{% block title %} Details {% endblock %}



{% block body%}



<div class="container-fluid">

    <div class="">
          <ol class="breadcrumb">
              <li><a href="#">Home</a></li>
              <li><a href="{% url 'music:index' %}">Albums</a></li>
              <li class="active">{{album.artist}}</li>
          </ol>
    </div>


    <div class="row">

        <div class="col-md-2">
              <div class="thumbnail">
                  <img src="{% static 'music/images/twitter-bird.png' %}" alt="..." width="120" height="120">
                  <div class="caption">
                    <h3>{{album.artist}}</h3>
                    <p>{{album.album_title}}</p>
                  </div>
            </div>
        </div>


        <div class="col-md-10">

            <div class="row">
                <div class="col-md-12">

                    <div class="breadcrumb">

                        <div class="container-fluid">

                            <div class="btn-group">
                                <button type="button" class="btn btn-primary btn-xs">Download All</button>
                                <button type="button" class="btn btn-primary btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <span class="caret"></span>
                                    <span class="sr-only">Toggle Dropdown</span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Action</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="#">Separated link</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <div class="row">

                <div class="col-md-12">

                    <table class="table table-striped table-bordered datatable " border="0" cellspacing="0" cellpadding="0">
                    <thead>
                        <tr>
                            <th>Song Name</th>
                            <th>File Type</th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>

                        {% for song in album.song_set.all %}

                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>{{ song.file_type }}</td>
                                <td>{{ song.album }}</td>
                            </tr>

                        {% endfor %}

                    </tbody>

                </table>



                </div>
            </div>

        </div>



    {% if error_message %}

        <p><strong>{{error_message}}</strong></p>

    {% endif %}

    </div>


</div>


{% endblock %}

bodos/templates/bodos/login.html
{% extends 'bodos/base.html' %}

{% load staticfiles %}

{% block title %} Login {% endblock %}


{% block body %}



<div class="wrapper">


      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">

            <!-- Main content -->
            <section class="content">


                <!--<body class="hold-transition register-page">-->


                <div class="register-box">

                      <div class="register-logo">
                            <a href="../../index2.html"><b>Admin</b>LTE</a>
                      </div>


                      <div class="register-box-body">

                            <p class="login-box-msg">Register a new membership</p>

                            <form action="{% url 'bodos:index' %}" method="post">
                                  <div class="form-group has-feedback">
                                    <input type="text" class="form-control" placeholder="Full name">
                                    <span class="glyphicon glyphicon-user form-control-feedback"></span>
                                  </div>


                                  <div class="form-group has-feedback">
                                    <input type="email" class="form-control" placeholder="Email">
                                    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                                  </div>


                                  <div class="form-group has-feedback">
                                    <input type="password" class="form-control" placeholder="Password">
                                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                                  </div>


                                  <div class="form-group has-feedback">
                                    <input type="password" class="form-control" placeholder="Retype password">
                                    <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
                                  </div>


                                  <div class="row">

                                    <div class="col-xs-8">
                                      <div class="checkbox icheck">
                                        <label>
                                          <input type="checkbox"> I agree to the <a href="#">terms</a>
                                        </label>
                                      </div>
                                    </div>
                                    <!-- /.col -->
                                    <div class="col-xs-4">
                                      <button type="submit" class="btn btn-primary btn-block btn-flat">Register</button>
                                    </div>
                                    <!-- /.col -->
                                  </div>

                            </form>

                            <div class="social-auth-links text-center">
                              <p>- OR -</p>
                              <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign up using
                                Facebook</a>
                              <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign up using
                                Google+</a>
                            </div>

                            <a href="login.html" class="text-center">I already have a membership</a>
                      </div>
                  <!-- /.form-box -->
                </div>




            </section>
            <!-- /.content -->

      </div>
      <!-- /.content-wrapper -->


</div>




{% endblock %}

bodos/templates/bodos/register.html
{% extends 'bodos/base.html' %}

{% load staticfiles %}

{% block title %} Login {% endblock %}


{% block body %}



<div class="wrapper">


      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">

            <!-- Main content -->
            <section class="content">


                <!--<body class="hold-transition register-page">-->


                <div class="register-box">

                  <!--<div class="register-logo">-->
                    <!--<a href="../../index2.html"><b>Admin</b>LTE</a>-->
                  <!--</div>-->


                  <div class="register-box-body">
                      <p class="login-box-msg">Register a new membership</p>

                      <form action="../../index.html" method="post">
                          <div class="form-group has-feedback">
                            <input type="text" class="form-control" placeholder="Full name">
                            <span class="glyphicon glyphicon-user form-control-feedback"></span>
                          </div>
                          <div class="form-group has-feedback">
                            <input type="email" class="form-control" placeholder="Email">
                            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                          </div>
                          <div class="form-group has-feedback">
                            <input type="password" class="form-control" placeholder="Password">
                            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                          </div>
                          <div class="form-group has-feedback">
                            <input type="password" class="form-control" placeholder="Retype password">
                            <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
                          </div>
                          <div class="row">
                            <div class="col-xs-8">
                              <div class="checkbox icheck">
                                <label>
                                  <input type="checkbox"> I agree to the <a href="#">terms</a>
                                </label>
                              </div>
                            </div>
                            <!-- /.col -->
                            <div class="col-xs-4">
                              <button type="submit" class="btn btn-primary btn-block btn-flat">Register</button>
                            </div>
                            <!-- /.col -->
                          </div>
                      </form>

                    <div class="social-auth-links text-center">
                      <p>- OR -</p>
                      <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign up using
                        Facebook</a>
                      <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign up using
                        Google+</a>
                    </div>

                    <a href="login.html" class="text-center">I already have a membership</a>
                  </div>
                  <!-- /.form-box -->
                </div>




            </section>
            <!-- /.content -->

      </div>
      <!-- /.content-wrapper -->


</div>




{% endblock %}